version: '3.7'

services:
    webserver:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./webserver:/webserver
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment:
            - DEBUG=1
        links:
            - mongo
        depends_on:
            - migration

    mongo:
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - ./mongo/data/db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mongoadmin
            MONGO_INITDB_DATABASE: raspicam
        ports:
            - "27017:27017"


    migration:
        build: .
        image: app
        command: sh -c "python manage.py migrate"
        volumes:
            - ./webserver:/webserver
        links:
            - mongo
        depends_on:
            - make_migrations

    make_migrations:
        build: .
        image: app
        command: sh -c "python manage.py makemigrations"
        volumes:
            - ./webserver:/webserver
        links:
            - mongo
        depends_on:
            - mongo